### ISSUE TITLE
Driver not functioning on Macbook10,1 running Manjaro 

### ISSUE THREAD

**Issue by NMLWright** [leifliddy/macbook12-audio-driver#9]
@leifliddy Greetings,

Just to preface, I'm not particularly familiar with Linux drivers. However, I was able to clone the package and install the cirrus driver without error. But when I reboot, the sound still doesn't work. I also tried your Macbook10-1-audio-driver-test too with the same issue. What information can I provide to help identify or debug the issue?

Thanks for making your work publicly available

**Comment by leifliddy** [comment]
I'm sure what the issue is. 
Two people have confirmed that this ```macbook12-audio-driver``` works on the macbook10,1, so you shouldn't need to use the ```macbook10-1-audio-driver-test``` driver.

https://github.com/leifliddy/macbook12-audio-driver/issues/6#issuecomment-756788207

https://github.com/leifliddy/macbook12-audio-driver/issues/6#issuecomment-596312920

Those two users were running Debian and Fedora respectively. I suspect that there might some os-level configuration issue with Manjaro, but I'm not sure. I would try installing this driver on either Debian or Fedora and see if that works.

Here are my notes on now to get a create a bootable Fedora liveusb stick with 4GB of persistant space

```
dnf install livecd-tools

# download fedora cinnamon

wget https://dl.fedoraproject.org/pub/alt/unofficial/releases/34/Fedora-Cinnamon-Live-x86_64-34-1.2.iso

livecd-iso-to-disk --format --reset-mbr --efi --overlay-size-mb 4095 Fedora-Cinnamon-Live-x86_64-34-1.2.iso /dev/sdd

--4095 is the largest overlay you can have...
**Can't have an overlay of 4095 MB or greater on VFAT


# to install newer kernel on usb stick
# create dracut config
echo -e 'hostonly="no"\nadd_dracutmodules+="dmsquash-live"' > /etc/dracut.conf.d/01-liveos.conf

# ensure latest kernel, kernel-headers, kernel-devel packages are installed
dnf upgrade kernel kernel-headers
dnf install git kernel-devel

# don't upgrade all packages otherwise the 4GB overlay partition might get overloaded
```
I'm sure you can figure out the rest. 
You'll obviously need to substitute ```/dev/sdd``` with the device id of your usb stick/device.
If Manjaro doesn't have ```livecd-iso-to-disk```  then just download the script here:
```wget https://github.com/livecd-tools/livecd-tools/blob/main/tools/livecd-iso-to-disk.sh``` 

Let me know if that works or not.
